USE u882331052_apitestenv;
DROP TABLE IF EXISTS failed_jobs;
DROP TABLE IF EXISTS migrations; 
DROP TABLE IF EXISTS password_resets; 
DROP TABLE IF EXISTS personal_access_tokens; 
DROP TABLE IF EXISTS users; 
DROP TABLE IF EXISTS tblVegetable; 
DROP TABLE IF EXISTS tblFruit; 
DROP TABLE IF EXISTS tblPlant_tblDateRangeFav; 
DROP TABLE IF EXISTS tblPlant_tblNbRangeFav; 
DROP TABLE IF EXISTS tblFavorites; 
DROP TABLE IF EXISTS tblPlant_tblProblem; 
DROP TABLE IF EXISTS tblPlant; 
DROP TABLE IF EXISTS tblPlantSowing; 
DROP TABLE IF EXISTS tblProblem; 
DROP TABLE IF EXISTS tblProfile; 
DROP TABLE IF EXISTS tblNbRangeFav;  
DROP TABLE IF EXISTS tblDateRangeFav;  